# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

# [START handlers]
handlers:
 - url: /
  static_files: build/index.html
  upload: build/index.html
  script: true
  secure: always
  redirect_http_response_code: 301
 

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]

skip_files:
 - ^node_modules/*.*
 - ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$